import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { Toaster } from "sonner";  

const inter = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: "TutorBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <GoogleOneTap />
          <Toaster /> 
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
